@echo off
REM Generated by trunk tool 'eslint'
set PATH=C:\Users\DELL\AppData\Local\trunk\tools\eslint\8.51.0-26a07e0553bc2ddf14d3c9621810eb4f/node_modules/.bin;C:\Users\DELL\AppData\Local\trunk\tools\node\18.12.1-ee91e409de31a08a96aaff7f742f83b4/bin;C:\Users\DELL\AppData\Local\trunk\tools\node\18.12.1-ee91e409de31a08a96aaff7f742f83b4;C:\Users\DELL\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\DELL\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set NODE_PATH=C:\Users\DELL\AppData\Local\trunk\tools\eslint\8.51.0-26a07e0553bc2ddf14d3c9621810eb4f/node_modules
set HOME=%HOME%
if not defined HOME set HOME=

start /w /b eslint %*
