@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\DELL\AppData\Local\trunk\tools\osv-scanner\1.4.1-2c7b768069fe958a8e898b409690e4d1;C:\Users\DELL\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\DELL\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
