@echo off
REM Generated by trunk tool 'trivy'
set PATH=C:\Users\DELL\AppData\Local\trunk\tools\trivy\0.45.1-e02772aa1468966b77c39672d3bd24ec;C:\Users\DELL\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\DELL\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trivy %*
