@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\DELL\AppData\Local\trunk\tools\trufflehog\3.59.0-cbf875388e366978316fb656074014be;C:\Users\DELL\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\DELL\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
