action_id: trunk-upgrade-available
date: 2023-10-16 12:37:42
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\r\n"
  err: ""
timestamp: 1697459862
full_timestamp:
  nanos: 421634000
  seconds: 1697459862
trunk_version: 1.17.0
